name: Python Unit Test
description: Python Unit Test report

inputs:
  PYTHON_VERSION:
    required: false
    default: "3.10"
    description: "Default Python version"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
        cache: 'pip'
    - run: pip install -r requirements.txt
