name: DependencyTrack dependencies analysys

inputs:
  DEPENDENCYTRACK_URL:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Generaing Bom
      uses: CycloneDX/gh-node-module-generatebom@master
    - uses: DependencyTrack/gh-upload-sbom@v2.0.1
      with:
        serverhostname: ${{ inputs.DEPENDENCYTRACK_URL }}
        apikey: ${{ env.DEPENDENCYTRACK_APIKEY }}
        projectname: ${{ github.repository }}
        projectversion: ${{ github.event.number }}
        autocreate: true