name: 'GCloud Auth'
description: 'Google Cloud Auth using Workload Identity Provider'

outputs:
  GCLOUD_TOKEN:
    value: ${{ steps.auth.outputs.access_token }}
    description: 'Access token from GCLOUD'

inputs:
  GCP_WIP:
    default: ""
    description: 'The workload identity provider.'
  PROJECT_ID:
    default: ""
    description: 'The project associated with the workload identity provider.'
runs:
  using: composite
  steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2.1.13'
      with:
        workload_identity_provider: ${{ inputs.GCP_WIP }}
        project_id: ${{ inputs.PROJECT_ID }}
    