name: 'GCloud Auth'
description: 'Google Cloud Auth using Workload Identity Provider'

runs:
  using: composite
  steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ env.GCP_WIP }}
        service_account: ${{ env.GCP_SA }}
    