name: 'GCloud Auth'
description: 'Google Cloud Auth using Workload Identity Provider'

outputs:
  GCLOUD_ACCESS_TOKEN:
    value: ${{ steps.random-number-generator.outputs.random-number }}
    description: 'Access token from GCLOUD'
runs:
  using: composite
  steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ env.GCP_WIP }}
        service_account: ${{ env.GCP_SA }}
    - id: random-number-generator
      run: echo "random-number=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      shell: bash
    