name: Build and pushing docker
description: Buld and push image to SignalWire registry

inputs:
  PROJECT_NAME:
    required: true
    description: 'Project naming matching registry repo'
  PUSH:
    required: false
    default: 'false'
    description: 'Whenever you want to push an image to regsitry'
  FILE:
    required: false
    default: ./Dockerfile
    description: 'Docker file location'
  CONTEXT:  
    required: false
    default: .
    description: 'Build context'
  PLATFORMS:
    required: false
    default: linux/amd64
    description: 'Target build platforms'
  TAG:
    required: false
    description: 'Image tag'
    default: |
      type=schedule
      type=ref,event=pr
      type=semver,pattern={{version}}
      type=semver,pattern={{major}}.{{minor}}
      type=semver,pattern={{major}}
      type=sha
  BUILD_ARGS:
    required: false
    default: ''
    description: 'Extra build args'
  REGISTRY:
    required: false
    default: 'registry.hub.docker.com'
    description: 'Registry URL'
  IMAGE_REPO:
    required: false
    default: 'signalwire'
    description: 'The default registry repo owner.'
  CONTAINER_TEST:
    default: 'true'
    description: 'Whenever the container should be tested on pr.'
    required: false
  CONTAINER_TEST_RUN_OPTIONS:
    default: ''
    description: 'Custom options for the docker run command that executes the test'
    required: false
  CONTAINER_TEST_COMMAND:
    default: ''
    description: 'A custom command to test the docker container.'
    required: false
  OUTPUT_TAG_INDEX:
    default: '0'
    description: 'Return a custom tag in case more than one is requested.'
    required: false
  TAG_ONLY:
    default: 'false'
    description: 'Generate tag only.'
    required: false
  ENABLE_CACHE:
    default: 'false'
    description: 'Whether to use cache when building the image'
    required: false
outputs:
  IMAGE_TAG:
    description: "Export image tag"
    value: ${{ steps.tag.outputs.IMAGE_TAG }}
    
runs:
  using: "composite"
  steps:
  
    - name: Configure buildx
      run: export DOCKER_CLI_EXPERIMENTAL=enabled && export DOCKER_TLS_CERTDIR="" && export DOCKER_HOST='docker'
      shell: bash

    - name: Configure buildx
      run: docker context create builders
      shell: bash
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.6.1
      with:
        version: latest
        endpoint: builders

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          signalwire/${{ inputs.PROJECT_NAME }}
        # generate Docker tags based on the following events/attributes
        tags: |
          ${{ inputs.TAG }}
    
    # - name: Login to ${{ inputs.REGISTRY }}
    #   uses: docker/login-action@v2
    #   if: contains(inputs.REGISTRY, 'pkg.dev' )
    #   with:
    #     registry: ${{ inputs.REGISTRY }}
    #     username: 'oauth2accesstoken'
    #     password: ${{ env.GCLOUD_ACCESS_TOKEN }}

    - name: Login to DockerHub
      uses: docker/login-action@v3
      if: inputs.TAG_ONLY == 'false'
      # if: contains(inputs.REGISTRY, 'docker.com' )
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}

    - name: Parse BUILD_ARGS if it's an input
      if: inputs.BUILD_ARGS != ''
      run: echo BUILD_ARGS=${{inputs.BUILD_ARGS}} >> $GITHUB_ENV
      shell: bash

    - name: Build and export to Docker without cache
      uses: docker/build-push-action@v6
      if: inputs.ENABLE_CACHE == 'false'
      with:
        load: true
        tags: |
          ${{ steps.meta.outputs.tags }}
        no-cache: true
        file: ${{ inputs.FILE }}
        context: ${{ inputs.CONTEXT }}
        # cannot use multiple platforms with `load`, build a single arch image for validation purposes in CI
        platforms: linux/amd64
        build-args: ${{ env.BUILD_ARGS }}
        secrets: ${{ env.DOCKER_SECRETS }}

    - name: Build and export to Docker with cache
      uses: docker/build-push-action@v6
      if: inputs.ENABLE_CACHE == 'true'
      with:
        load: true
        tags: |
          ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        no-cache: false
        file: ${{ inputs.FILE }}
        context: ${{ inputs.CONTEXT }}
        # cannot use multiple platforms with `load`, build a single arch image for validation purposes in CI
        platforms: linux/amd64
        build-args: ${{ env.BUILD_ARGS }}
        secrets: ${{ env.DOCKER_SECRETS }}

    - name: Test
      if: github.event_name == 'pull_request' && inputs.CONTAINER_TEST == 'true' && inputs.TAG_ONLY == 'false'
      id: test
      shell: bash
      run: |
        docker images
        echo "Starting container for image: ${{ steps.meta.outputs.tags }}"
        docker run -d --rm --name test ${{ inputs.CONTAINER_TEST_RUN_OPTIONS }} ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
        sleep 20
        docker ps
        docker logs test
        ${{ inputs.CONTAINER_TEST_COMMAND }}
    
    - name: Build and push with cache
      if: inputs.PUSH == 'true' && inputs.ENABLE_CACHE == 'true'
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        no-cache: false
        file: ${{ inputs.FILE }}
        context: ${{ inputs.CONTEXT }}
        platforms: ${{ inputs.PLATFORMS }}
        build-args: ${{ env.BUILD_ARGS }}
        secrets: ${{ env.DOCKER_SECRETS }}

    - name: Build and push without cache
      if: inputs.PUSH == 'true' && inputs.ENABLE_CACHE == 'false'
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
        file: ${{ inputs.FILE }}
        no-cache: true
        context: ${{ inputs.CONTEXT }}
        platforms: ${{ inputs.PLATFORMS }}
        build-args: ${{ env.BUILD_ARGS }}
        secrets: ${{ env.DOCKER_SECRETS }}
          
    # - name: Scanning image
    #   if: github.event_name == 'pull_request'
    #   run: docker sbom --output sbom.json ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
    #   shell: bash

    - name: Exporting image tag
      run: echo "IMAGE_TAG=${{ fromJSON(steps.meta.outputs.json).tags[inputs.OUTPUT_TAG_INDEX] }}" >> $GITHUB_OUTPUT
      id: tag
      shell: bash
