name: Build artifacts using Dockerfile

inputs:
  REPO_DOMAIN:
    required: false
    description: Domain name of repository
  PLATFORM:
    required: true
    description: Default Linux Arch (amd64/arm32v7/...)
  DOCKERFILE:
    required: true
    description: Path to Dockerfile
  MAINTAINER:
    required: true
    description: Package maintainer
  WORKING_DIRECTORY:
    required: true
    default: "."
    description: Working directory
  ARTIFACTS_PATTERN:
    required: false
    default: '.*\.(deb|rpm)$'
    description: Regexp that matches artifacts
  ARTIFACTS_DIR:
    required: false
    default: "BUILD"
    description: Output directory for artifacts
  BUILD_LOG_FILENAME:
    required: false
    default: "build.log"
    description: Build log filename

runs:
  using: "composite"
  steps:
    - name: Wait for Docker daemon
      shell: bash
      run: |
        until docker info >/dev/null 2>&1; do
          if [ $SECONDS -ge 60 ]; then
            echo "Timeout waiting for Docker daemon"
            exit 1
          fi
          sleep 1
        done

    - name: Set up QEMU for Docker
      uses: docker/setup-qemu-action@v3
      with:
        cache-image: false

    - name: Build Docker image
      shell: bash
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      env:
        REPO_USERNAME: ${{ env.REPO_USERNAME }}
        REPO_PASSWORD: ${{ env.REPO_PASSWORD }}
        DEPLOYMENT_TOKEN: ${{ env.DEPLOYMENT_TOKEN }}
      run: |
        BUILD_ARGS=(
          --build-arg BUILD_NUMBER="${GITHUB_RUN_ID}"
          --build-arg GIT_SHA="$(echo ${GITHUB_SHA} | cut -c1-10)"
          --build-arg MAINTAINER="${{ inputs.MAINTAINER }}"
          --build-arg REPO_DOMAIN="${{ inputs.REPO_DOMAIN }}"
          --build-arg REPO_USERNAME="${{ env.REPO_USERNAME }}"
          --file "${{ inputs.DOCKERFILE }}"
          --platform linux/${{ inputs.PLATFORM }}
          --progress=plain
          --secret id=REPO_PASSWORD,env=REPO_PASSWORD
          --secret id=DEPLOYMENT_TOKEN,env=DEPLOYMENT_TOKEN
          --tag artifacts-${GITHUB_RUN_ID}:${GITHUB_SHA}
          --ulimit nofile=1024000:1024000
          --pull
        )

        if docker buildx version >/dev/null 2>&1; then
          docker buildx create --use --name larger_log \
            --driver-opt env.BUILDKIT_STEP_LOG_MAX_SIZE=50000000 || true

          docker buildx build "${BUILD_ARGS[@]}" --load \
          . 2>&1 | tee -a ${{ inputs.BUILD_LOG_FILENAME }}

          docker buildx rm larger_log || true
        else
          docker build "${BUILD_ARGS[@]}" --force-rm \
          . 2>&1 | tee -a ${{ inputs.BUILD_LOG_FILENAME }}
        fi

    - name: Upload build log
      if: failure()
      uses: actions/upload-artifact@v6
      with:
        name: build-log-${{ github.run_id }}-${{ github.sha }}
        path: ${{ inputs.WORKING_DIRECTORY }}/${{ inputs.BUILD_LOG_FILENAME }}
        retention-days: 7
        if-no-files-found: ignore

    - name: Extract artifacts from image
      shell: bash
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: |
        set -euo pipefail

        # create container from image and export filesystem
        container_id=$(docker create artifacts-${GITHUB_RUN_ID}:${GITHUB_SHA} sh)
        mkdir -p "${{ inputs.ARTIFACTS_DIR }}"
        docker export "$container_id" | tar -xf - -C "${{ inputs.ARTIFACTS_DIR }}"
        find "${{ inputs.ARTIFACTS_DIR }}" -type d -empty -delete

        # cleanup
        docker rm "$container_id"
        docker image rm artifacts-${GITHUB_RUN_ID}:${GITHUB_SHA}

        if [ "$(find "${{ inputs.ARTIFACTS_DIR }}" -type f | wc -l)" -lt 1 ]; then
            echo "No files found in ${{ inputs.ARTIFACTS_DIR }}."
            exit 1
        fi

    - name: Filter artifacts by pattern
      shell: bash
      working-directory: ${{ inputs.WORKING_DIRECTORY }}
      run: |
        set -euo pipefail

        export TEMP_DIR=$(mktemp -d)

        find "${{ inputs.ARTIFACTS_DIR }}" \
          -type f \
          -regextype posix-extended \
          -regex "${{ inputs.ARTIFACTS_PATTERN }}" \
          -exec sh -c 'mv -vf "$1" "${TEMP_DIR}/$(basename "$1")"' _ {} \; && \
        rm -rvf "${{ inputs.ARTIFACTS_DIR }}" && \
        mv -v "${TEMP_DIR}" "${{ inputs.ARTIFACTS_DIR }}"

        if [ "$(find "${{ inputs.ARTIFACTS_DIR }}" -type f | wc -l)" -lt 1 ]; then
            echo "No files found in ${{ inputs.ARTIFACTS_DIR }}."
            exit 1
        fi

        printf ${GITHUB_SHA} | tee "${{ inputs.ARTIFACTS_DIR }}/hash.txt"
