name: Helm local deploy
description: Deploy a local Helm Chart to a Kubernetes Cluster

inputs:
  APP_NAME:
    required: true
  CHART_PATH:
    required: true
  NAMESPACE:
    required: true
  VALUES_FILE:  
    required: true
        
runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: 3.9.0
    
    - name: Helm upgrade --install
      run: helm upgrade ${{ inputs.APP_NAME }} ${{ inputs.CHART_PATH }} --install --create-namespace --namespace=${{ inputs.NAMESPACE }} -f=${{ inputs.VALUES_FILE }}
      shell: bash
