name: Helm local deploy
description: Deploy a local Helm Chart to a Kubernetes Cluster

inputs:
  APP_NAME:
    required: true
    description: Kubernetes app name.
  CHART_PATH:
    required: true
    description: Chart path as context
  NAMESPACE:
    required: true
    description: Namespace where the app will be deployed
  VALUES_FILE:  
    required: true
    description: Default values file

runs:
  using: "composite"
  steps:
    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: 3.9.0
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ inputs.CHART_PATH }}/charts
        key: ${{ runner.os }}-${{ inputs.CHART_PATH }}

    - name: Fetch dependencies
      run: helm dep update ${{ inputs.CHART_PATH }}
      shell: bash

    - name: Helm upgrade --install with --set
      if: env.INLINE_VALUES != ''
      run: helm upgrade ${{ inputs.APP_NAME }} ${{ inputs.CHART_PATH }} --install --create-namespace --namespace=${{ inputs.NAMESPACE }} -f=${{ inputs.VALUES_FILE }} --set ${{ env.INLINE_VALUES }}
      shell: bash
    
    - name: Helm upgrade --install
      if: env.INLINE_VALUES == ''
      run: helm upgrade ${{ inputs.APP_NAME }} ${{ inputs.CHART_PATH }} --install --create-namespace --namespace=${{ inputs.NAMESPACE }} -f=${{ inputs.VALUES_FILE }}
      shell: bash
