#!/bin/bash
# Create a production deployment branch and PR in a GitOps repository.
#
# Usage: ./create-prod-pr.sh [options]
#   --service-name NAME        Service name (e.g., my-service)
#   --branch-name NAME         Branch name for the PR (e.g., my-service/2026-01-28T10-30-00Z)
#   --new-image-tag TAG        New Docker image tag
#   --new-sha SHA              New git SHA
#   --old-image-tag TAG        Previous Docker image tag
#   --old-sha SHA              Previous git SHA
#   --repo REPO                Target GitOps repo (e.g., org/gitops-prod)
#   --source-repo REPO         Source repo for comparison links (e.g., org/my-service)
#   --stack-file PATH          Path to stack file in GitOps repo
#   --docker-repo REPO         Docker repository (e.g., org/my-service)
#   --base-branch BRANCH       Base branch for PR (default: main)
#   --dry-run                  Show what would be done without creating PR
#
# Environment variables (for multiline content):
#   DEPLOY_REASON              Reason for deployment
#   PR_LIST                    Markdown list of PRs included

set -euo pipefail

DRY_RUN=false
SERVICE_NAME=""
BRANCH_NAME=""
NEW_IMAGE_TAG=""
NEW_SHA=""
OLD_IMAGE_TAG=""
OLD_SHA=""
REPO=""
SOURCE_REPO=""
STACK_FILE=""
DOCKER_REPO=""
BASE_BRANCH="main"

while [[ $# -gt 0 ]]; do
  case $1 in
    --service-name)   SERVICE_NAME="$2"; shift 2 ;;
    --branch-name)    BRANCH_NAME="$2"; shift 2 ;;
    --new-image-tag)  NEW_IMAGE_TAG="$2"; shift 2 ;;
    --new-sha)        NEW_SHA="$2"; shift 2 ;;
    --old-image-tag)  OLD_IMAGE_TAG="$2"; shift 2 ;;
    --old-sha)        OLD_SHA="$2"; shift 2 ;;
    --repo)           REPO="$2"; shift 2 ;;
    --source-repo)    SOURCE_REPO="$2"; shift 2 ;;
    --stack-file)     STACK_FILE="$2"; shift 2 ;;
    --docker-repo)    DOCKER_REPO="$2"; shift 2 ;;
    --base-branch)    BASE_BRANCH="$2"; shift 2 ;;
    --dry-run)        DRY_RUN=true; shift ;;
    *) echo "::error::Unknown option: $1"; exit 1 ;;
  esac
done

REASON="${DEPLOY_REASON:-}"
PR_LIST_CONTENT="${PR_LIST:-}"

: "${SERVICE_NAME:?--service-name is required}"
: "${BRANCH_NAME:?--branch-name is required}"
: "${NEW_IMAGE_TAG:?--new-image-tag is required}"
: "${NEW_SHA:?--new-sha is required}"
: "${OLD_IMAGE_TAG:?--old-image-tag is required}"
: "${OLD_SHA:?--old-sha is required}"
: "${REASON:?DEPLOY_REASON environment variable is required}"
: "${REPO:?--repo is required}"
: "${STACK_FILE:?--stack-file is required}"

: "${DOCKER_REPO:?--docker-repo is required}"
: "${SOURCE_REPO:?--source-repo is required}"

if [[ -z "$PR_LIST_CONTENT" ]]; then
  PR_LIST_CONTENT="*No PRs found between versions*"
fi

# Check if branch already exists.
if git ls-remote --exit-code --heads origin "$BRANCH_NAME" >/dev/null 2>&1; then
  echo "::error::Branch $BRANCH_NAME already exists in $REPO."
  echo "A deployment PR may already be open: https://github.com/${REPO}/pulls?q=is%3Apr+head%3A${BRANCH_NAME}"
  exit 1
fi

git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

if [[ "$DRY_RUN" == "true" ]]; then
  echo "=== DRY RUN MODE ==="
  echo ""
  echo "Would create branch: $BRANCH_NAME"
  echo "Would update file: $STACK_FILE"
  echo "  - image: ${DOCKER_REPO}:${NEW_IMAGE_TAG}"
  echo "  - GIT_SHA: ${NEW_SHA}"
  echo ""
else
  git checkout -b "$BRANCH_NAME"

  # Update image tag using yq for proper YAML handling.
  # Find and update any image value matching the docker repo.
  yq eval -i "
    (.services[].image | select(contains(\"${SERVICE_NAME}\"))) = \"${DOCKER_REPO}:${NEW_IMAGE_TAG}\"
  " "$STACK_FILE"

  # Update GIT_SHA in environment sections.
  yq eval -i "
    (.. | select(has(\"GIT_SHA\")).GIT_SHA) = \"${NEW_SHA}\"
  " "$STACK_FILE"

  git add "$STACK_FILE"
  git commit -m "[${SERVICE_NAME}] Update image to ${DOCKER_REPO}:${NEW_IMAGE_TAG}"
  git push origin "$BRANCH_NAME"
fi

# Build PR body with rich deployment context.
PR_BODY="## :rocket: Production Deployment: ${SERVICE_NAME}

### Image Info

| | Image | GIT_SHA |
|---|---|---|
| **New** | \`${DOCKER_REPO}:${NEW_IMAGE_TAG}\` | \`${NEW_SHA}\` |
| **Previous** | \`${DOCKER_REPO}:${OLD_IMAGE_TAG}\` | \`${OLD_SHA}\` |

### Reason for Deploy

${REASON}

### Changes

:mag: [Full Commit Comparison](https://github.com/${SOURCE_REPO}/compare/${OLD_SHA}...${NEW_SHA})

#### Pull Requests Included

${PR_LIST_CONTENT}

### Pre-Merge Checklist

- [ ] Verified the Docker image exists and is ready for production
- [ ] Reviewed the included PRs for any deployment-sensitive changes
- [ ] Confirmed no conflicting deployments are in progress
- [ ] Service name is in the PR/commit title (for deployment channel visibility)

---
*This PR was automatically generated by the deploy-prod workflow.*"

PR_TITLE="[${SERVICE_NAME}] Update image to ${DOCKER_REPO}:${NEW_IMAGE_TAG}"

if [[ "$DRY_RUN" == "true" ]]; then
  echo "Would create PR:"
  echo "  Title: $PR_TITLE"
  echo "  Base:  $BASE_BRANCH"
  echo "  Head:  $BRANCH_NAME"
  echo ""
  echo "PR Body:"
  echo "=========================================="
  echo "$PR_BODY"
  echo "=========================================="
  echo ""
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    echo "pr_url=DRY_RUN_NO_PR_CREATED" >> "$GITHUB_OUTPUT"
  fi
else
  PR_BODY_FILE=$(mktemp)
  echo "$PR_BODY" > "$PR_BODY_FILE"

  PR_URL=$(gh pr create \
    --repo "$REPO" \
    --title "$PR_TITLE" \
    --body-file "$PR_BODY_FILE" \
    --base "$BASE_BRANCH" \
    --head "$BRANCH_NAME")

  rm -f "$PR_BODY_FILE"
  echo "Created PR: $PR_URL"
  if [[ -n "${GITHUB_OUTPUT:-}" ]]; then
    echo "pr_url=$PR_URL" >> "$GITHUB_OUTPUT"
  fi
fi
