name: Push to CI
description: Push image tag to CI

inputs:
  GITOPS_REPOSITORY:
    description: 'The GitOps repository to push to'
    required: true
  FILE_PATH:
    description: 'The file path in the GitOps repository to update'
    required: true
  SERVICE_NAME:
    description: 'The name of the service to update'
    required: true
  IMAGE_TAG:
    description: 'The new image tag to push'
    required: true
  ORCHESTRATOR:
    required: true
    default: swarm
    description: The orchestrator to deploy to.
  CREATE_PR:
    required: true
    description: Create a PR instead of pushing directly to the branch.
  BRANCH_NAME:
    required: false
    description: The branch name to create if CREATE_PR is true.

runs:
  using: "composite"
  steps:
    - name: Checkout GitOps repo
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.GITOPS_REPOSITORY }}
        token: ${{ env.GITOPS_PAT }}    
        ref: ${{ github.head_ref }}   

    - name: Create new branch
      if: ${{ inputs.CREATE_PR == 'true' }}
      run: git switch -C ${{ inputs.BRANCH_NAME }}
      shell: bash

    - name: Update image tag in GitOps repo for Swarm
      shell: bash
      if: ${{ inputs.ORCHESTRATOR == 'swarm' }}
      env:
        FILE_PATH: ${{ inputs.FILE_PATH }}
        SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
      run: |
        sed -i 's|image: signalwire/$SERVICE_NAME:[^ ]*|image: $IMAGE_TAG|' $FILE_PATH
    
    - name: Update image tag in GitOps repo for Kubernetes
      shell: bash
      if: ${{ inputs.ORCHESTRATOR == 'kubernetes' }}
      env:
        FILE_PATH: ${{ inputs.FILE_PATH }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
      run: |
         sed -i "s/^  tag: .*/  tag: $IMAGE_TAG/" "$FILE_PATH"

    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "[${{ inputs.SERVICE_NAME }}] Update image tag to ${{ inputs.IMAGE_TAG }}"
        repository: ${{ inputs.GITOPS_REPOSITORY }}
        commit_user_name: ${{ github.actor }}
        commit_user_email: ${{ github.actor }}@users.noreply.github.com

    - name: Create PR
      shell: bash
      if: ${{ inputs.CREATE_PR }}
      run: |
          gh pr create --title "Update image tag for ${{ inputs.SERVICE_NAME }}" --body "Update image tag for ${{ inputs.SERVICE_NAME }}" --base main --head ${{ inputs.BRANCH_NAME }}

    
