name: Dasel
description: short for data-selector

runs:
  using: "composite"
  steps:

    - uses: actions/cache@v3
      name: Restore cache
      id: cache
      with:
        path: ./dasel
        key: ${{ runner.os }}-dasel
        restore-keys: |
          ${{ runner.os }}-dasel
    
    - name: Install Dasel
      if: steps.cache.outputs.cache-hit != 'true'
      run: curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
      shell: bash

    # Leave it static for now
    - name: Run validation
      run: |
        mkdir -p toml/labeled_configs
        mv labeled_base.conf ./toml/labeled_base.toml
        for file in labeled_configs/*.conf; do mv -- "$file" "toml/$file.toml";done
        ./dasel validate toml/*.toml toml/labeled_configs/*.toml
      shell: bash
