name: .NET Unit Test
description: .NET Test report

inputs:
  DOTNET_VERSION:
    required: false
    default: "6.0.403"
    description: .NET version
  RUN_TESTS:
    required: false
    default: 'true'
    description: Whenever you wanna run tests.

runs:
  using: "composite"
  steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.DOTNET_VERSION }}

    - name: test docker-compose
      run: docker ps
      shell: bash
      
    - name: Build
      run: sudo dotnet build --configuration Release
      shell: bash
    
    - name: Rename .env
      run: rename .env.ci .env
      shell: bash
      continue-on-error: true

    - name: Test
      run: sudo dotnet test --logger "trx;LogFileName=test-results.trx" -p:DefineConstants=TESTING || true
      if: inputs.RUN_TESTS != 'false'
      shell: bash

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always() && inputs.RUN_TESTS == 'true'
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
