name: .NET Unit Test
description: .NET Test report

inputs:
  DOTNET_VERSION:
    required: false
    default: "6.0.403"
    description: .NET version
  GENERATE_DEV_CERTS:
    required: false
    type: boolean
    default: false
    description: Generate dev-certs for https
  RUN_TESTS:
    required: false
    default: 'true'
    description: Whenever you wanna run tests.
  DOTNET_INSTALL_DIR:
    required: false
    default: './.dotnet'
    description: Set a custom .NET install dir

runs:
  using: "composite"
  steps:
    # - name: Cache dotnet
    #   id: cache-dotnet
    #   uses: actions/cache@v3
    #   with:
    #     path: ${{ inputs.DOTNET_INSTALL_DIR }}
    #     key: ${{ runner.os }}-dotnet-7
    #     restore-keys: ${{ runner.os }}-dotnet-7

    - name: Setup .NET Core
      # if: ${{ steps.cache-dotnet.outputs.cache-hit != 'true' }}
      uses: actions/setup-dotnet@v3.1.0
      with:
        dotnet-version: ${{ inputs.DOTNET_VERSION }}
      env:
        DOTNET_INSTALL_DIR: ${{ inputs.DOTNET_INSTALL_DIR }}

    - name: test docker-compose
      run: docker ps
      shell: bash
    
    - name: debug
      run: ls -la
      shell: bash

    - name: Generate a self-signed certificate to enable HTTPS
      if: inputs.GENERATE_DEV_CERTS
      run: sudo dotnet dev-certs https -v
      shell: bash
      continue-on-error: true

    - name: Build
      run: sudo dotnet build --configuration Release
      shell: bash
    
    - name: Rename .env
      run: mv .env.ci .env
      shell: bash
      continue-on-error: true

    - name: Test
      run: sudo dotnet test --logger "trx;LogFileName=test-results.trx" -p:DefineConstants=LOCALTESTING || true
      if: inputs.RUN_TESTS != 'false'
      shell: bash

    - name: Workaround tests
      run: chown runner:docker -R **/test-results.trx
      shell: bash
      continue-on-error: true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always() && inputs.RUN_TESTS == 'true'
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true
