name: Trivy scan
description: Trivy docker container vulnerability assessment

inputs:
  IMAGE:
    required: true
  TRIVY_IGNORES:
    required: false
    
runs:
  using: "composite"
  steps:
  - uses: lazy-actions/gitrivy@v3
    with:
      token: ${{ env.GITHUB_TOKEN }}
      image: ${{ inputs.IMAGE }}
      severity: HIGH
      trivy_version: "0.22.0"
      trivyignores: ${{ inputs.TRIVY_IGNORES}}