name: Trivy scan
description: Trivy docker container vulnerability assessment

inputs:
  IMAGE:
    required: true
    
runs:
  using: "composite"
  steps:
  - uses: aquasecurity/trivy-action@master
    with:
      image-ref: ${{ inputs.IMAGE }}
      format: 'table'
      severity: 'HIGH,CRITICAL'
      exit-code: '0'
      ignore-unfixed: true
      vuln-type: 'os,library'
      output: container_scan.txt 
