name: Trivy scan
description: Trivy docker container vulnerability assessment

inputs:
  IMAGE:
    required: true
  PROJECT_NAME:
    required: true
    
runs:
  using: "composite"
  steps:

  - uses: aquasecurity/trivy-action@master
    id: scan
    continue-on-error: true
    with:
      image-ref: ${{ inputs.IMAGE }}
      template: "@actions/.github/actions/trivy/template.tpl"
      format: template
      severity: 'HIGH,CRITICAL'
      exit-code: '1'
      ignore-unfixed: true
      vuln-type: 'os,library'
      output: container_scan.txt

  - name: Load plan file
    id: read
    if: steps.scan.outcome != 'success'
    uses: juliangruber/read-file-action@v1
    with:
      path: container_scan.txt 

  - name: Create Issue on container scan
    uses: dacbd/create-issue-action@v1
    if: steps.scan.outcome != 'success'
    with:
      title: Vulnerability Detected ${{inputs.PROJECT_NAME}}
      token: ${{ env.PAT }}
      repo: cloud-product
      body: >
        ### Context
        [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
        Workflow name - `${{ github.workflow }}`
        Job -           `${{ github.job }}`
        status -        `${{ job.status }}`
        Vulnerabilities -
        
        ${{ steps.read.outputs.content }}
      assignees: ${{ github.actor }}
      labels: team/devops,security,vulnerability,docker
