name: Trivy scan
description: Trivy docker container vulnerability assessment

inputs:
  IMAGE:
    required: true
    
runs:
  using: "composite"
  steps:
  - uses: aquasecurity/trivy-action@master
    with:
      image-ref: ${{ inputs.IMAGE }}
      format: 'table'
      severity: 'HIGH,CRITICAL'
      fail_on_vulnerabilities: false
      exit-code: '1'
      ignore-unfixed: true
      vuln-type: 'os,library'
      output: container_scan.txt 

  - run: cat container_scan.txt
    shell: bash

  - name: Load plan file
    id: read
    uses: juliangruber/read-file-action@v1
    with:
      path: container_scan.txt 

  - name: Create Issue on container scan
    if: ${{ failure() }}
    uses: dacbd/create-issue-action@main
    with:
      token: ${{ env.PAT }}
      title: Vulnerability Detected
      org: signalwire
      repo: cloud-product
      body: |
        ### Context
        [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
        [Codebase](https://github.com/${{ github.repository }}/tree/${{ github.sha }})
        Workflow name - `${{ github.workflow }}`
        Job -           `${{ github.job }}`
        status -        `${{ job.status }}`
        Vulnerabilities - `${{ steps.read.outputs.content }}`
      assignees: ${{ github.actor }}