name: Push libs metadata to another Git repo

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
        description: Environment where the variables and secrets are scoped to
      RUNNER:
        required: false
        default: ubuntu-latest
        type: string
        description: A GitHub runner type
      ARTIFACT_NAME:
        required: false
        default: ''
        description: The artifact name to pull from a previous step
        type: string
      FILE_PATH:
        required: true
        default: ''
        description: File full-path
        type: string
      TARGET_REPO:
        required: true
        default: ''
        description: Target repo to sync changes.
        type: string
      LIB_NAME:
        required: true
        default: ''
        type: string
        description: Lib name that will be used as target branch.
    secrets:
      GH_BOT_DEPLOY_TOKEN:
        required: false
        description: 'Personal access token used to fetch submodules.'
      GH_BOT_DEPLOY_KEY:
        required: false
        description: Key used to clone private repos

jobs:
  sync:

    runs-on: ${{ inputs.RUNNER }}
    name: Sync metadata for ${{inputs.LIB_NAME}} at ${{inputs.FILE_PATH}}/${{inputs.ARTIFACT_NAME}}
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - name: Checkout metadatarepo
        uses: actions/checkout@v3
        id: metabranch
        with:
          repository: ${{ inputs.TARGET_REPO }}
          ref: ${{ inputs.LIB_NAME }}
          ssh-key: ${{ secrets.GH_BOT_DEPLOY_KEY }}
          token: ${{ secrets.GH_BOT_DEPLOY_TOKEN || github.token }}
      
      - name: Create remote
        continue-on-error: true
        run: |
          git checkout -b ${{ inputs.LIB_NAME }}
          touch metadata.txt
          git push --set-upstream origin ${{ inputs.LIB_NAME }}

      - name: Sync changes
        run: |
          git checkout ${{ inputs.LIB_NAME }}
          echo "${{inputs.FILE_PATH}}/${{inputs.ARTIFACT_NAME}}" >> metadata.txt
          git add metadata.txt
          git push