name: Docker tagging

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
      RUNNER:
        required: false
        default: ubuntu-latest
        type: string
      SOURCE_TAG:
        description: Docker source tag
        required: false
        type: string
        default: |
          type=schedule
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha
      TARGET_TAG:
        description: Docker target tag
        required: true
        type: string
      PROJECT_NAME:
        required: true
        description: Project naming matching registry repo
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: true
        description: 'DockerHub username.'
      DOCKERHUB_TOKEN:
        required: true
        description: 'DockerHub PAT.'

jobs:
  deploy:

    runs-on: ${{ inputs.RUNNER }}
    name: Tagging
    environment: ${{ inputs.ENVIRONMENT }}

    steps:

    - name: Checkout actions
      uses: actions/checkout@v4
      with:
        repository: signalwire/actions-template
        ref: main
        path: actions

    - uses: cloudposse/github-action-matrix-outputs-read@main
      id: read
      with:
        matrix-step-name: build

    - uses: ./actions/.github/actions/docker
      name: Docker build
      id: dockertag
      with:
        PROJECT_NAME: ${{ inputs.PROJECT_NAME }}
        TAG: ${{ inputs.TARGET_TAG }}
        TAG_ONLY: true
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: filter
      run: |
        filtered_output='${{steps.read.outputs.result}}'
        echo SOURCE_TAG=$(echo $filtered_output | jq '.image."${{inputs.PROJECT_NAME}}"' -r) >> $GITHUB_ENV

    - uses: ./actions/.github/actions/docker-tag-clone
      name: Copy docker tag
      with:
        TARGET_TAG: ${{ steps.dockertag.outputs.IMAGE_TAG }}
        SOURCE_TAG: ${{ env.SOURCE_TAG }}
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}