# This is a basic workflow to help you get started with Actions

name: Swarm Deploy

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      STACK_NAME:
        required: true
        type: string
        description: Stack name on Portainer.
      APPROVERS:
        required: false
        type: string
        description: A list of approvers comma separated.
      IMAGE_TAG:
        required: true
        type: string
        description: The image tag to be updated.
      ENVIRONMENT:
        required: false
        type: string
        description: The environment which this deploy refers to.
      RUNNER: 
        required: false
        type: string
        default: ubuntu-latest
        description: The default runner.
      NOTIFY_SLACK:
        required: false
        type: boolean
        default: true
      SLACK_CHANNEL:
        required: false
        type: string
        description: Default slack channel to post a message
      ENDPOINT_ID:
        required: false
        type: string
        description: Another option to set ENDPOINT_ID.
        default: ''
      PORTAINER_DOMAIN:
        required: true
        type: string
        description: Portainer Domain
        default: deploy.signalwire.cloud
      PORTAINER_DOMAIN_PROTOCOL:
        required: false
        type: string
        description: Portainer Protocol
        default: http
    secrets:
      ENDPOINT_ID:
        required: false
        description: Portainer Endpoint ID.
      PORTAINER_API_KEY:
        required: true
        description: Portainer API KEY.
      GH_APPROVAL_APP_ID:
        required: false
        description: App ID for Approval
      GH_APPROVAL_APP_PKEY:
        required: false
        description: App Key for Approval
      SLACK_WEBHOOK_URL:
        required: true
        description: Slack WebHook URL

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.RUNNER }}
    name: Deploy to Swarm
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Checkout actions
      uses: actions/checkout@v4
      with:
        repository: signalwire/actions-template
        ref: main
        path: actions
        
    - name: Push to CI
      uses: ./actions/.github/update/push-to-ci
      with:
        GITOPS_REPOSITORY: ${{ inputs.GITOPS_REPOSITORY }}
        FILE_PATH: ${{ inputs.FILE_PATH }}
        SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
        IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
      env: 
        GITOPS_PAT: ${{ secrets.GITOPS_PAT }}