# This is a basic workflow to help you get started with Actions

name: Build RPM Packages

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
      RUNNER:
        required: false
        default: ubuntu-latest
        type: string
      PROJECT_NAME:
        required: true
        type: string
      RUN_BACKGROUND:
        required: false
        type: string
        default: 'false'
      PACKAGER:
        required: false
        type: string
        default: 'false'
      PLATFORM:
        required: false
        description: Default OS/Arch
        default: amd64
        type: string
      TARGET_ARTIFACT_NAME:
        required: false
        description: Artifact name.
        default: centos
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

jobs:
  deploy:

    runs-on: ${{ inputs.RUNNER }}
    name: Build
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      with:
        fetch-depth: 0

    - name: Build RPM Packages
      uses: signalwire/build-rpm-packages-action@dev
      with:
        project_name: ${{inputs.PROJECT_NAME}}
        packager: ${{inputs.PACKAGER}}
    
    - name: Generate hash file
      run: echo $GITHUB_SHA > hash.txt
      env:
        GITHUB_SHA: ${{ github.sha }}

    - name: Compress files
      run: |
        tar -czvf ${{inputs.TARGET_ARTIFACT_NAME}}.tar.gz $(ls | grep '.rpm\|hash.txt')

    - name: Generate SHA checksum
      run: |
        sha512sum ${{inputs.TARGET_ARTIFACT_NAME}}.tar.gz > ${{inputs.TARGET_ARTIFACT_NAME}}.sha1
      
    - uses: actions/upload-artifact@v3
      with:
        name: rpm-${{inputs.PLATFORM}}-artifact
        path: |
          *.tar.gz
          *.sha1